#!/usr/bin/env bash
# Configuring server web02 to communicate with web01
if ! command -v nginx > /dev/null 2>&1; then
	sudo apt-get update
	sudo apt-get install -y nginx
	ufw allow "Nginx HTTP"
fi

HOSTNAME=$(hostname)

NGINX_CONFIG="/etc/nginx/sites-available/default"

# inserting the variable 
sudo sed -i '/^ *server *{/,/^ *}$/s/^\( *server *{\)/\1\n    add_header X-Served-By '"$HOSTNAME"';/' "$NGINX_CONFIG"

sudo service nginx start
