#!/usr/bin/env bash
# HAproxy, the load balancer

# HAproxy installation
sudo apt-get update
sudo apt-get -y install haproxy

# Configure to use roundrubin algorithm
echo '
frontend reinhardbett.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 111545-web-01 54.158.219.223:80
        server 111545-web-02 100.25.31.47:80
' >> /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAproxy with service
sudo service haproxy restart
