#!/usr/bin/env bash
# This script automates a MySQL dumb and creates a compressed archive out of it
# The MySQL dump must contain all MySQL databases
# The MySQL dump must be named backup.sql
# The MySQL dump file has to be compressed to a tar.gz archive
# This archive must have the following name format: day-month-year.tar.gz
# The user to connect to the MySQL database must be root
# The Bash script accepts one argument that is the password used to connect to the MySQL database
mysqldump -u root -p"$1" --all-databases > backup.sql
date_output=$(date +%d-%m-%Y)
tar -czf "$date_output.tar.gz" backup.sql
