#!/usr/bin/env bash
# Configure local machine to connect to server without password

Host 54.160.122.53
    HostName 54.160.122.53
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
